spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: GUEST-SERVICE
          uri: lb://GUEST-SERVICE
          predicates:
            - Path=/api/guest/**
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
