spring:
  application:
    name: gateway-service
#  main:
#    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: guest-service
          uri: lb://GUEST-SERVICE
          predicates:
            - Path=/api/guest/**
        - id: hotel-service
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/api/hotel/**
        - id: reservation-service
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/api/reservation/**
        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/api/auth/**
    discovery:
      enabled: true
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
